# Generated by Django 6.0.5 on 2026-05-15 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('UPLOAD_PDF', 'Uploaded PDF'), ('UPLOAD_IMG', 'Uploaded Image'), ('API_FETCH', 'API Fetch'), ('OCR_SCAN', 'OCR Scan')], max_length=50)),
                ('date_issued', models.DateField()),
                ('source_hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('raw_api_payload', models.JSONField(blank=True, null=True)),
                ('ocr_extracted_text', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
