# Generated by Django 6.0.5 on 2026-05-15 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('GLUCOSE', 'Glucose'), ('CHOLESTEROL', 'Cholesterol'), ('BP_SYS', 'Blood Pressure (Systolic)'), ('BP_DIA', 'Blood Pressure (Diastolic)'), ('HEART_RATE', 'Heart Rate')], max_length=50)),
                ('value_numeric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('measured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
