# Generated by Django 6.0.5 on 2026-05-15 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='healthmetric',
            index=models.Index(fields=['user', 'metric_type', 'measured_at'], name='metrics_hea_user_id_0cd9f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthmetric',
            constraint=models.CheckConstraint(condition=models.Q(('value_numeric__gt', 0)), name='value_numeric_positive'),
        ),
    ]
