# Generated by Django 6.0.5 on 2026-05-15 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFitnessSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_steps', models.IntegerField(default=0)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('avg_spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WearableIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('APPLE_HEALTH', 'Apple Health'), ('GOOGLE_FIT', 'Google Fit'), ('GARMIN', 'Garmin')], max_length=50)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
