# Generated by Django 6.0.5 on 2026-05-15 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfitnesssummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wearableintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailyfitnesssummary',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_fitness'),
        ),
    ]
