# Generated by Django 6.0.5 on 2026-05-15 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MEDICINE', 'Medicine'), ('VACCINATION', 'Vaccination'), ('CHECKUP', 'Checkup')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('due_datetime', models.DateTimeField()),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
