# Generated by Django 6.0.5 on 2026-05-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='chronic_conditions',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='_allergies_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='_chronic_conditions_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
